# # Site settings
# title: "Jekyll Resume Template"
# description: "A resume template for Jekyll and GitHub Pages sites."

# # Build settings
# markdown: kramdown
# sass:
#   sass_dir: _sass
#   style: compressed

# # Resume settings
# resume_avatar:                  "true"
# resume_name:                    "Lisa M. Simpson"
# resume_title:                   "VP of Global Communications"

# # used for the contact button in _layouts/resume.html
# resume_contact_email:           "lisasimpson@youremailaddress.com"

# # the next two items are used for schema itemprops in _layouts/resume.html
# resume_contact_telephone:       "555-7334"
# resume_contact_address:         "742 Evergreen Terrace, Springfield"

# resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
# display_header_contact_info:    "false"

# resume_header_intro: "<p>This is the executive summary. You should write a few brief, concise, and meaningful sentences about yourself from a professional context, and your immediate career goals. Make the length appropriate for your needs, but keep it brief and concise</p>"

# # use "yes" to display the email contact button,
# # "no" to display an "I'm not looking for work" message,
# # or remove the resume_looking_for_work option entirely
# # to leave blank
# resume_looking_for_work:        "yes"

# # Decide which sections to use
# # comment out to hide
# resume_section_experience:      true
# resume_section_education:       true
# resume_section_projects:        true
# resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# # resume_section_interests:       true

# # Resume social links
# # uncomment the options you wish to display, and add your own URL
# resume_social_links:
#   resume_github_url:            "https://github.com/jglovier/resume-template"
#   resume_twitter_url:           "http://twitter.com/jglovier"
#   resume_dribbble_url:          "https://dribbble.com/jag"
#   # resume_facebook_url:          "insert Facebook URL here"
#   resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
#   # resume_instagram_url:         "insert your Instagram URL here"
#   resume_website_url:           "http://joelglovier.com"
#   resume_medium_url:            "https://medium.com/@jglovier"
# resume_print_social_links:      true

# # Design settings
# resume_theme:                   default

# # Note: when editing locally, remember to restart
# # your Jekyll server when you edit this file. Changes
# # to _config.yml are only recognized when the server starts

# Site settings
title: "Avinash Kharat CV"
description: "Avinash Kharat's professional resume hosted on GitHub Pages."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Avinash Raju Kharat"
resume_title:                   "MCA Student at National Institute of Technology, Raipur"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "kharatavinashraju8@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+91-7387021564"
resume_contact_address:         "Ulhasnagar, Maharashtra, India"

resume_header_contact_info:     "Ulhasnagar, Maharashtra, India • +91-7387021564 • kharatavinashraju8@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "Motivated MCA student with a strong foundation in computer science, experienced in developing web and mobile applications. Seeking opportunities to leverage my technical skills and contribute to innovative projects."

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      false
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    false
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/kharatsonu358"
  # resume_twitter_url:           "insert your Twitter URL here"
  # resume_dribbble_url:          "insert your Dribbble URL here"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/avinash-kharat-7926151b4/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://leetcode.com/Avinash_kharat/"
  # resume_medium_url:            "insert your Medium URL here"
resume_print_social_links:      true

# Design settings
resume_theme:                   default
